#!/usr/bin/env python3
"""Rebuilds the JSON-LD block in site/index.html from the page itself.

The FAQ answers exist twice — once as prose a person reads, once as
structured data a machine reads — and the second copy is worthless the
moment it stops matching the first. So it isn't maintained: it is
generated from the markup, between two marker comments, and the check
below fails the build if the block on disk is out of date.

Run from the repo root:  python3 site/scripts/build-jsonld.py [--check]
"""
import html
import json
import re
import sys
from pathlib import Path

PAGE = Path("site/index.html")
BEGIN = "<!-- JSON-LD: generated by site/scripts/build-jsonld.py — do not edit by hand -->"
END = "<!-- /JSON-LD -->"

SITE = "https://openpdfedit.com/"
APP = "https://app.openpdfedit.com/"
REPO = "https://github.com/open-pdf-edit/OpenPdfEdit"


def text_of(fragment: str) -> str:
    """Tag-stripped, whitespace-collapsed, entities resolved."""
    return re.sub(r"\s+", " ", html.unescape(re.sub(r"<[^>]+>", "", fragment))).strip()


def faq_entries(source: str) -> list[dict]:
    blocks = re.findall(
        r'<h3 class="faq-q">(.*?)</h3>\s*<p class="faq-a">(.*?)</p>',
        source,
        flags=re.S,
    )
    if not blocks:
        sys.exit("no FAQ entries found — has the markup changed?")
    return [
        {
            "@type": "Question",
            "name": text_of(q),
            "acceptedAnswer": {"@type": "Answer", "text": text_of(a)},
        }
        for q, a in blocks
    ]


def tool_names(source: str) -> list[str]:
    """Every tool the page lists, for `featureList`.

    Taken from the same markup the page renders, so the claim a machine
    reads and the claim a reader sees cannot disagree about what the
    product does.
    """
    # `.tool-name` wraps the name and, for the paid two, a "Supporter"
    # badge. Only the name is the feature: "Watermark Supporter" is not
    # a thing the product does.
    raw = re.findall(r'<span class="tool-name">(.*?)</span>\s*<span class="tool-desc">', source, re.S)
    names = [text_of(re.sub(r'<span class="tool-tag">.*?</span>', "", n, flags=re.S)) for n in raw]
    # The statement block up top reuses .tool-name for four promises
    # ("Nothing is uploaded"), which are not tools.
    return [n for n in names if not n.startswith(("Nothing is", "No account", "No watermarks", "No AI"))]


def graph(source: str) -> dict:
    publisher = {
        "@type": "Organization",
        "@id": SITE + "#publisher",
        "name": "OpenPdfEdit",
        "url": SITE,
        "sameAs": [REPO],
    }
    return {
        "@context": "https://schema.org",
        "@graph": [
            publisher,
            {
                "@type": "WebSite",
                "@id": SITE + "#website",
                "url": SITE,
                "name": "OpenPdfEdit",
                "publisher": {"@id": SITE + "#publisher"},
                "inLanguage": "en",
            },
            {
                "@type": "SoftwareApplication",
                "@id": SITE + "#app",
                "name": "OpenPdfEdit",
                "url": SITE,
                "applicationCategory": "BusinessApplication",
                "applicationSubCategory": "PDF editor",
                "operatingSystem": "macOS, Windows, Web browser, Chrome",
                "softwareVersion": VERSION,
                "license": "https://opensource.org/licenses/MIT",
                "isAccessibleForFree": True,
                "downloadUrl": REPO + "/releases/latest",
                "installUrl": APP,
                "publisher": {"@id": SITE + "#publisher"},
                "image": SITE + "og.png",
                "description": (
                    "A PDF editor that runs on your own machine. Annotate, edit text, redact, "
                    "fill and sign forms, reorganise pages, OCR scans and compare drafts — "
                    "documents are never uploaded."
                ),
                # Free, with two named tools behind a one-time payment.
                # Stating both is what keeps "free" from being a lie by
                # omission when an answer engine quotes it flatly.
                "offers": [
                    {
                        "@type": "Offer",
                        "name": "OpenPdfEdit",
                        "price": "0",
                        "priceCurrency": "USD",
                        "description": "Every tool except watermarking and OCR.",
                    },
                    {
                        "@type": "Offer",
                        "name": "Supporter tools",
                        "description": (
                            "Watermarking and OCR, unlocked together with a single one-time "
                            "payment of 1,000 credits."
                        ),
                    },
                ],
                "featureList": tool_names(source),
            },
            {"@type": "FAQPage", "@id": SITE + "#faq", "mainEntity": faq_entries(source)},
        ],
    }


VERSION = json.loads(Path("apps/desktop/package.json").read_text())["version"]


def main() -> None:
    source = PAGE.read_text()
    block = (
        BEGIN
        + '\n<script type="application/ld+json">\n'
        + json.dumps(graph(source), indent=2, ensure_ascii=False)
        + "\n</script>\n"
        + END
    )

    if BEGIN in source:
        start = source.index(BEGIN)
        end = source.index(END) + len(END)
        updated = source[:start] + block + source[end:]
    else:
        anchor = "</head>"
        updated = source.replace(anchor, block + "\n" + anchor, 1)

    if "--check" in sys.argv:
        if updated != source:
            sys.exit("site/index.html's JSON-LD is stale — run: python3 site/scripts/build-jsonld.py")
        print("JSON-LD is up to date")
        return

    PAGE.write_text(updated)
    print(f"wrote JSON-LD ({len(faq_entries(source))} FAQ entries, "
          f"{len(tool_names(source))} features)")


if __name__ == "__main__":
    main()
