#![no_main]

// Fuzzes `openpdfedit_doc::Document::from_bytes` — the entry point every
// untrusted PDF a user opens goes through. PLAN.md §9 calls this out
// explicitly: "PDFs are an attack surface; fuzz `openpdfedit-doc` and the
// engine boundary from day one." A parse *error* on malformed input is
// correct and expected; a panic, OOM, or hang is a real bug.
//
// Run with: `cargo +nightly fuzz run parse_document`
// Seed corpus: point at ../../../../testdata/corpus (fetched by
// scripts/fetch-test-corpus.sh) via `-corpus <dir>`, or copy files into
// `corpus/parse_document/` — see fuzz/README generated by cargo-fuzz.

use libfuzzer_sys::fuzz_target;
use openpdfedit_doc::Document;

fuzz_target!(|data: &[u8]| {
    let _ = Document::from_bytes(data);
});
