// The Chrome extension `Backend` implementation: `openpdfedit-wasm`'s
// `WasmSession` (see crates/openpdfedit-wasm/src/lib.rs) called
// in-process, no IPC. Phase 1's wasm surface was deliberately narrow — see
// task-8-brief.md's amendment: read-render-save only, no undo/redo (the
// mutate/undo pathway used to be filesystem-bound, and wasm documents live
// in memory with no working copy to speak of). That constraint is gone as
// of the `WorkingStore` abstraction (Phase 2, Task 1 — see the Rust module
// doc for `MemWorkingStore`): `WasmSession` now exposes the same
// annotation/undo/redo surface `tauri.ts` does
// (`addAnnotation`/`deleteAnnotation`/`listPageAnnotations`/
// `textSelectionQuads`/`undo`/`redo`), wired in below (Phase 2, Task 4).
// Forms/pages (Phase 3, Task 3) and signatures/redact/textedit/image
// (Phase 4, Task 3) surfaces are wired in too, the same way, and
// multi-file merge/compare (Phase 5, Task 2) closes out the surface:
// `mergeDocuments`/`compareDocuments` are real now too. The only `Backend`
// method that still throws is `ocrDocument` — genuinely unavailable in
// this backend, not just unported; see `notAvailableInExtension` below.
//
// This file replaces Task 7's permanent placeholder (a `Proxy` that threw
// on every method) — see that commit's fix-round entry in
// task-7-report.md for why `wasm.ts` had to exist as a real, resolvable
// module even before this task landed. `index.ts`'s `import("./wasm")`
// (a literal specifier, no `@vite-ignore`) is untouched by this change —
// it already resolves this file correctly in both build directions
// (verified in Task 7); nothing here needs it to change.

import type {
  AddAnnotationRequest,
  AnnotationSummaryDto,
  Backend,
  CompareDocumentsRequest,
  CompareReportDto,
  CreateFormFieldRequest,
  DeleteAnnotationRequest,
  EditTextRunRequest,
  ExtractPagesRequest,
  FillFormFieldsRequest,
  FormFieldDto,
  ImagePlacementDto,
  MergeDocumentsRequest,
  MoveImageRequest,
  MoveTextRunRequest,
  OpenedDocument,
  PageBitmap,
  PageMoveDirection,
  RedactPageRequest,
  ApplyWatermarkRequest,
  CompressDocumentRequest,
  CompressStats,
  SearchResultsDto,
  SignatureInfoDto,
  TextRunDto,
  TextSelectionQuadsRequest,
} from "./types";

// --- Asset-layout contract ------------------------------------------
//
// This module needs two things to exist as real HTTP-fetchable assets,
// at runtime, relative to the extension origin root (`chrome-extension://
// <id>/...` — a leading `/` below resolves against that origin from any
// page inside the extension, regardless of how deeply nested the page
// itself is). `apps/extension/scripts/build-spa.sh` is what actually
// wires this up today: it builds this app with `VITE_BACKEND=wasm`, then
// merges the result into `apps/extension/dist/` on top of what
// `apps/extension`'s own `vite.config.js`/`copy-vendor.sh` already put
// there (see that script's header for the full pipeline, and
// `apps/desktop/src/hooks.ts` for the `reroute` fix that makes the merged
// `index.html` actually resolve to this app's `/` route once loaded from
// `chrome-extension://<id>/index.html`):
//
//   1. `/pdfium.js` (+ the `/pdfium.wasm` it fetches itself) — PDFium's
//      Emscripten glue, vendored from pdfium-lib and copied into the
//      extension's dist by `apps/extension/scripts/copy-vendor.sh`. Must
//      be reachable as a classic (non-module) script — see
//      `loadPdfiumScript` below for why this file injects a <script> tag
//      itself instead of relying on some HTML shell's static <script>
//      tag (which this module doesn't get to assume exists, or ran
//      before this code did).
//   2. `/wasm-gen/openpdfedit_wasm.js` (+ its paired
//      `openpdfedit_wasm_bg.wasm`, which the glue module fetches relative
//      to its own URL — no separate reference needed here) — the
//      wasm-bindgen `--target web` output of `crates/openpdfedit-wasm`,
//      generated by `apps/extension/scripts/build-wasm.sh` into
//      `apps/extension/src/wasm-gen/`. This module imports it by a
//      **runtime** relative-URL string (see `WASM_GLUE_MODULE_PATH`
//      below), not a static `import` — the file does not exist anywhere
//      under `apps/desktop` (this app doesn't run `build-wasm.sh`; it
//      only ever gets copied into the merged `apps/extension/dist/`
//      output), so a static/literal specifier would fail both
//      `npm run check` and every `vite build` in this app, the same
//      failure `index.ts`'s own doc comment documents for a
//      `/* @vite-ignore */`-routed specifier. Routing through a `const`
//      variable + `/* @vite-ignore */` here is the right tool for the
//      opposite reason `index.ts` rejected it for its *own* import of
//      this file: `index.ts` needs Vite to actually resolve and bundle
//      `wasm.ts` for real (a literal specifier), while this import must
//      stay a genuine, unresolved-at-build-time runtime import, because
//      the target file never exists in `apps/desktop`'s own build output
//      — only in the merged extension `dist/` this app's build result
//      gets copied into.
//
// Neither dynamic import below is ever reached by `apps/desktop`'s own
// build or typecheck (see `initSession`'s doc for how `npm run check`/
// `VITE_BACKEND=wasm npm run build` both stay green without ever running
// this module's init sequence) — they only resolve for real once this
// app's build output is merged into `apps/extension/dist/` by
// `build-spa.sh` and loaded as the unpacked extension.
const PDFIUM_SCRIPT_PATH = "/pdfium.js";
const WASM_GLUE_MODULE_PATH = "/wasm-gen/openpdfedit_wasm.js";

// --- Ambient ammunition the installed TypeScript's `lib.dom.d.ts` is
// missing (confirmed the same gap `apps/extension/editor.ts` found and
// documented: `showOpenFilePicker`/`showSaveFilePicker` aren't declared
// on `Window` in the `typescript@5.6.3` this repo has installed, even
// though `FileSystemFileHandle`/`FileSystemWritableFileStream` — which
// *are* used below — already are). Declared narrowly, just the one
// overload each call site here actually uses, rather than pulling in
// `@types/wicg-file-system-access` for it. ------------------------------
declare global {
  interface Window {
    showOpenFilePicker(options?: {
      multiple?: boolean;
      types?: { description?: string; accept: Record<string, string[]> }[];
    }): Promise<FileSystemFileHandle[]>;
    showSaveFilePicker(options?: {
      suggestedName?: string;
      types?: { description?: string; accept: Record<string, string[]> }[];
    }): Promise<FileSystemFileHandle>;
    /** Set by a classic (non-module) `<script src="/pdfium.js">` —
     * `loadPdfiumScript` injects that tag itself; see its doc. Optional
     * because nothing has necessarily loaded it yet at the type level. */
    PDFiumModule?: () => Promise<unknown>;
  }
}

// --- The shape this module needs from the wasm-bindgen `--target web`
// glue module, typed by hand since the dynamic import below can't carry
// real types across a runtime-string specifier (see the asset-layout
// comment above). Keep in sync with crates/openpdfedit-wasm/src/lib.rs's
// actual `#[wasm_bindgen]` surface — nothing enforces this statically,
// the way it would if the import were real; a mismatch fails at runtime,
// not at typecheck time.
//
// This stays hand-typed rather than importing the real generated
// `apps/extension/src/wasm-gen/openpdfedit_wasm.d.ts` (which does
// accurately describe `WasmSession` today — it's regenerated by
// `apps/extension/scripts/build-wasm.sh` on every wasm build, not
// checked in) because that file is gitignored and doesn't exist in a
// fresh `apps/desktop` checkout that hasn't run the extension's wasm
// build: a static `import type` of it would break `npm run check`/
// `vite build` here whenever it's absent, which is most of the time for
// this app (`apps/desktop` never runs `build-wasm.sh` itself — see the
// asset-layout comment above). If this interface ever needs to be
// double-checked against the real thing, regenerate it
// (`bash apps/extension/scripts/build-wasm.sh` from the repo root) and
// diff `apps/extension/src/wasm-gen/openpdfedit_wasm.d.ts` against the
// three interfaces below by hand.
//
// Last diffed against a real `bash apps/extension/scripts/build-wasm.sh`
// build in Phase 5 Task 2 (see that task's report for the full diff
// output): `WasmSessionHandle` was missing `mergeDocuments`/
// `compareDocuments`, now added below with the same signatures
// (`request_json`/`sources_buffer`/`bytes_a`/`bytes_b`/`options_json`
// camelCased here for consistency with the rest of this interface, same
// as every prior diff note). Both match what was designed and hand-typed
// before generating: `mergeDocuments(requestJson: string, sourcesBuffer:
// Uint8Array): Uint8Array` and `compareDocuments(bytesA: Uint8Array,
// bytesB: Uint8Array, optionsJson: string): string` — no surprises this
// time.
//
// Previously diffed in Phase 4 Task 3 (see that task's report for the
// fuller diff output): `WasmSessionHandle` was missing the seven signatures/redact/
// textedit/image methods the regenerated `.d.ts` already declared on
// `WasmSession` (`listSignatures`, `redactPage`, `listTextRuns`,
// `editTextRun`, `moveTextRun`, `listImagePlacements`, `moveImage` — the
// crate-side surface landed a commit earlier, in `openpdfedit-wasm`, ahead
// of this file catching up), now added below with the same signatures
// (param names camelCased here for consistency with the rest of this
// interface, same as every prior diff note). No new non-cosmetic type
// gaps this time — every one of these seven takes only plain `number`
// arguments or a JSON `string` (no `Float32Array`/enum-narrowing case like
// `setCropBox`/`movePage` needed).
//
// Previously diffed in Phase 3 Task 3 (see that task's report for the
// fuller diff output):
// `WasmSessionHandle` below was missing the eight forms/pages methods the
// regenerated `.d.ts` already declared on `WasmSession` (`listFormFields`,
// `fillFormFields`, `createFormField`, `rotatePage`, `deletePage`,
// `movePage`, `setCropBox`, `extractPages` — the crate-side surface landed
// a commit earlier, in `openpdfedit-wasm`, ahead of this file catching
// up), now added below with the same signatures (param names camelCased
// here for consistency with the rest of this interface — cosmetic only;
// the generated `.d.ts` itself uses `page_index`/`delta_degrees`/etc.
// since that's `#[wasm_bindgen]`'s default, un-renamed Rust parameter
// naming — only method names go through `js_name`). Two real (not merely
// cosmetic) types worth calling out since they aren't obvious from the
// method name alone: `movePage`'s `direction` is a plain `string` in the
// generated `.d.ts` (typed narrower here as `PageMoveDirection`, since
// `MoveDirection`'s wire form is always exactly `"Up"`/`"Down"` — see the
// Rust doc on `WasmSession::move_page`), and `setCropBox`'s `rect` is a
// `Float32Array`, not a plain `number[]` — wasm-bindgen's `&[f32]`
// parameter marshals a JS typed array only, so this backend's own
// `setCropBox` call site below must build one (`Float32Array.from(...)`)
// rather than pass `rect` through as-is.
//
// Previously diffed in Phase 2 Task 4 (see that task's report for the
// fuller diff output): `WasmSessionHandle` was missing all six
// annotation/undo methods (`addAnnotation`, `deleteAnnotation`,
// `listPageAnnotations`, `textSelectionQuads`, `undo`, `redo`), added then
// with the same camelCasing convention. The only other gap, still true
// today: the real `WasmSession`/`RenderedPage` classes also carry a
// wasm-bindgen-generated `[Symbol.dispose](): void` (from the
// `#[wasm_bindgen]` macro's default `Symbol.dispose` binding to `free()`)
// that neither hand-typed interface below declares — harmless, since
// nothing in this file uses `using`/explicit-resource-management to call
// it, and TypeScript's structural typing doesn't require an unused
// interface to declare every member the real object happens to have. ---

/** `RenderedPage`'s wasm-bindgen-generated shape — getters, not plain
 * fields (matches `#[wasm_bindgen(getter)]` in the Rust struct), plus
 * the `free()` wasm-bindgen generates on every exported class to run its
 * `Drop` impl and release its wasm-linear-memory bytes deterministically
 * — see `getPageBitmap` below, which calls it right after reading the
 * fields it needs instead of waiting on GC (there is none for wasm
 * linear memory; an un-freed `RenderedPage` leaks until the whole
 * `WasmSession`/module is torn down). */
interface RenderedPageHandle {
  readonly width: number;
  readonly height: number;
  readonly pointWidth: number;
  readonly pointHeight: number;
  readonly rgba: Uint8Array;
  free(): void;
}

/** `WasmSession`'s exported methods. Every method is synchronous (no
 * `async fn` exports — see the Rust module doc for why) and throws a
 * plain string-valued exception on the Rust side's `Err`, per
 * wasm-bindgen's `Result<T, JsValue>` convention. `handle` is a plain JS
 * `number` everywhere, not `bigint` — see `WasmSession`'s own Rust doc
 * comment for why `u32` was chosen over wasm-bindgen's `u64`-as-`bigint`
 * mapping. */
interface WasmSessionHandle {
  openDocument(displayName: string, bytes: Uint8Array): string;
  /** A full PDFium rewrite of the in-memory document — NOT what saving
   * should write to disk (see `workingCopyBytes` below, and its Rust doc,
   * for why: a full rewrite can restructure the whole file and breaks the
   * incremental-save/signature-preservation invariant). Kept for any
   * caller that genuinely wants a full engine-side rewrite; this backend's
   * own save path does not. */
  saveToBytes(handle: number): Uint8Array;
  /** The working-copy bytes `commit_mutation`/`undo_impl`/`redo_impl` last
   * wrote for `handle`'s document — an incremental (append-only) save,
   * exactly what the desktop backend's own `save_document_impl` writes to
   * disk. This, not `saveToBytes`, is what this backend's save path
   * (`writeToFileHandle`) must use to byte-match the desktop's save
   * output. See `WasmSession::working_copy_bytes`'s Rust doc for the full
   * rationale. */
  workingCopyBytes(handle: number): Uint8Array;
  /** Flips the session's real `is_dirty` bit back to `false` — see
   * `WasmSession::mark_saved`'s Rust doc for the caller contract (only
   * call this once the bytes `saveToBytes` returned have actually been
   * durably written; never speculatively, never after a failed write).
   * Returns the same `OpenedDocumentInfo` JSON shape `openDocument` does. */
  markSaved(handle: number): string;
  renderPage(handle: number, pageIndex: number, targetWidth: number): RenderedPageHandle;
  /** Real `WasmSession` method (`openpdfedit_session::PageSize[]` JSON —
   * see `WasmSession::page_sizes`'s Rust doc), declared here for
   * completeness even though nothing in this file calls it today: every
   * `Backend` method that returns an `OpenedDocument` already carries its
   * own `page_sizes` field (see `parseOpenedDocument`), which is what
   * `+page.svelte`'s virtualized layout actually reads. Kept as a real,
   * typed entry point rather than removed, since a future caller that
   * wants a page-size refresh without a full `openDocument`/mutate round
   * trip can call it directly — this interface's job is to describe what
   * the real generated class exposes, not just what this file happens to
   * use (see the block comment above this interface for the same
   * reasoning re: `[Symbol.dispose]`). */
  pageSizes(handle: number): string;
  closeDocument(handle: number): void;
  /** Mutating — returns `OpenedDocumentInfo` JSON under a **rotated**
   * handle, same as every other mutating method below (see
   * `openpdfedit-session::reopen_after_write`'s doc: it closes the old
   * engine-side handle itself). `requestJson` is the same
   * `AddAnnotationRequest` JSON `tauri.ts` sends `add_annotation_cmd`
   * (it already carries its own `handle` field, so there's no separate
   * `handle` parameter here). */
  addAnnotation(requestJson: string): string;
  /** Mutating/rotates, same as `addAnnotation` above. `requestJson` is a
   * `DeleteAnnotationRequest`. */
  deleteAnnotation(requestJson: string): string;
  /** Read-only — no handle rotation. Returns an
   * `AnnotationSummaryDto[]` JSON array. */
  listPageAnnotations(handle: number, pageIndex: number): string;
  /** Read-only — no handle rotation. `requestJson` is a
   * `TextSelectionQuadsRequest`; returns a `[number, number, number,
   * number][]` JSON array of quads. */
  textSelectionQuads(requestJson: string): string;
  /** Mutating/rotates, same as `addAnnotation` above. */
  undo(handle: number): string;
  /** Mutating/rotates, same as `addAnnotation` above. */
  redo(handle: number): string;
  /** Read-only — no handle rotation. Returns a `FormFieldDto[]` JSON
   * array. */
  listFormFields(handle: number): string;
  /** Mutating/rotates, same as `addAnnotation` above. `requestJson` is a
   * `FillFormFieldsRequest`. */
  fillFormFields(requestJson: string): string;
  /** Mutating/rotates, same as `addAnnotation` above. `requestJson` is a
   * `CreateFormFieldRequest`. */
  createFormField(requestJson: string): string;
  /** Mutating/rotates. Plain `handle`/`pageIndex`/`deltaDegrees`
   * arguments, not a request JSON — mirrors `rotate_page_cmd`'s own bare
   * `State` + scalar arguments on the desktop side (no request DTO exists
   * for it). */
  rotatePage(handle: number, pageIndex: number, deltaDegrees: number): string;
  /** Mutating/rotates. Plain `handle`/`pageIndex` arguments — see
   * `rotatePage`'s doc for why. */
  deletePage(handle: number, pageIndex: number): string;
  /** Mutating/rotates. Plain `handle`/`pageIndex`/`direction` arguments —
   * see `rotatePage`'s doc for why. `direction` is always exactly
   * `"Up"`/`"Down"` on the wire (see `WasmSession::move_page`'s Rust doc),
   * narrowed here to `PageMoveDirection` rather than the generated
   * `.d.ts`'s plain `string`. */
  movePage(handle: number, pageIndex: number, direction: PageMoveDirection): string;
  /** Mutating/rotates. Plain `handle`/`pageIndex`/`rect` arguments — see
   * `rotatePage`'s doc for why. `rect` must be a `Float32Array`
   * (`[x0, y0, x1, y1]`), not a plain `number[]` — wasm-bindgen's `&[f32]`
   * Rust parameter marshals a JS typed array only. */
  setCropBox(handle: number, pageIndex: number, rect: Float32Array): string;
  /** Read-only against the source document — no handle rotation, and
   * returns the **extracted document's raw bytes**, not `OpenedDocumentInfo`
   * JSON, unlike every other mutating method above. See
   * `WasmSession::extract_pages`'s Rust doc (and this file's own
   * `extractPages` implementation below) for why: there is no filesystem
   * here for a new document to open from the way the desktop's
   * `extract_pages_cmd` does, so this backend turns the returned bytes
   * into a real `OpenedDocument` itself, via a second `openDocument` call
   * against a `FileSystemFileHandle` its caller already picked.
   * `requestJson` carries only `{ handle, pageIndices }` — no
   * `outputPath`, unlike `types.ts`'s `ExtractPagesRequest`, since this
   * method has no filesystem path to write. */
  extractPages(requestJson: string): Uint8Array;
  /** Read-only — no handle rotation. Returns a `SignatureInfoDto[]` JSON
   * array (structural inspection only — `isVerified` is always `false`,
   * see the Rust doc on `WasmSession::list_signatures`). */
  listSignatures(handle: number): string;
  /** Read-only — no handle rotation. Returns a `SearchResultsDto` JSON
   * string. Takes plain arguments rather than a request JSON blob
   * because every one of them is a primitive. */
  searchDocument(
    handle: number,
    query: string,
    matchCase: boolean,
    wholeWord: boolean,
  ): string;
  /** Mutating/rotates, same as `addAnnotation` above. `requestJson` is a
   * `RedactPageRequest`. */
  redactPage(requestJson: string): string;
  applyWatermark(requestJson: string): string;
  /** Read-only — no handle rotation. Returns a `TextRunDto[]` JSON
   * array. */
  listTextRuns(handle: number, pageIndex: number): string;
  /** Mutating/rotates, same as `addAnnotation` above. `requestJson` is an
   * `EditTextRunRequest`. */
  editTextRun(requestJson: string): string;
  /** Mutating/rotates, same as `addAnnotation` above. `requestJson` is a
   * `MoveTextRunRequest`. */
  moveTextRun(requestJson: string): string;
  /** Read-only — no handle rotation. Returns an `ImagePlacementDto[]`
   * JSON array. */
  listImagePlacements(handle: number, pageIndex: number): string;
  /** Mutating/rotates, same as `addAnnotation` above. `requestJson` is a
   * `MoveImageRequest`. */
  moveImage(requestJson: string): string;
  /** Read-only against the currently-open document at `requestJson`'s
   * `openHandle` (if given) — no handle rotation, same "no filesystem to
   * open a new document from" situation as `extractPages` above, so this
   * returns the merged document's raw bytes, not `OpenedDocumentInfo`
   * JSON — see `WasmSession::merge_documents`'s Rust doc for the full
   * wasm-boundary design rationale. `requestJson` carries only
   * `{ openHandle: number | null }`. `sourcesBuffer` is a flat
   * length-prefixed concatenation — `[u32 length, little-endian][that
   * many bytes]` per extra source, in order — built by this file's own
   * `packLengthPrefixedSources` below; wasm-bindgen can't marshal a
   * `Vec<Vec<u8>>` directly, and this was the simpler of the two designs
   * the Rust doc considers (the other being a stateful two-step
   * beginMerge/addMergeSource/finishMerge API). */
  mergeDocuments(requestJson: string, sourcesBuffer: Uint8Array): Uint8Array;
  /** Read-only, no handle involved at all — neither document needs to
   * already be open in this session (matching the desktop's
   * `compare_documents_cmd`). Returns a `CompareReportDto` JSON string.
   * `optionsJson` carries only `{ pixelTargetWidth: number | null }` —
   * omit/`null` skips pixel-diff mode entirely (text-only compare needs
   * no PDFium round trip). See `WasmSession::compare_documents`'s Rust
   * doc and this file's own `compareDocuments` implementation below for
   * how `bytesA`/`bytesB` get sourced without any change to `types.ts`'s
   * `CompareDocumentsRequest` shape. */
  compareDocuments(bytesA: Uint8Array, bytesB: Uint8Array, optionsJson: string): string;
}

interface WasmModuleExports {
  /** wasm-bindgen `--target web`'s default export: fetches and
   * instantiates the paired `.wasm` (relative to the glue module's own
   * URL) when called with no arguments. */
  default: () => Promise<unknown>;
  initialize_pdfium_render: (pdfiumModule: unknown, rustModule: unknown, debug: boolean) => boolean;
  WasmSession: new () => WasmSessionHandle;
}

// --- Init sequence: PDFium's wasm module -> the wasm-bindgen glue's own
// init -> initialize_pdfium_render -> construct WasmSession. Moved here
// from `apps/extension/editor.ts` (which Task 9 retires), same ordering
// and the same hard-won comments about why each step is what it is — see
// that file's header for the fuller archaeology (which JS/wasm asset
// pair, why `init()`'s return value is the right second argument for
// `initialize_pdfium_render`) that isn't repeated verbatim here. --------

/** Injects PDFium's Emscripten glue as a classic (non-module) `<script>`
 * tag and waits for it to run. Not a static `<script>` tag in some HTML
 * shell this module can assume exists (unlike `editor.html` today) —
 * per task-8-brief.md point 4, this module owns the whole init sequence
 * itself rather than relying on HTML script ordering Task 9 hasn't
 * designed yet. A classic script (not `type="module"`) is required
 * because `pdfium.js` is Emscripten's "MODULARIZE=1 EXPORT_NAME=
 * PDFiumModule" UMD output — its top-level `var PDFiumModule = ...`
 * only becomes `window.PDFiumModule` when it runs as a non-module
 * script. */
function loadPdfiumScript(): Promise<void> {
  return new Promise((resolve, reject) => {
    const script = document.createElement("script");
    script.src = PDFIUM_SCRIPT_PATH;
    script.onload = () => resolve();
    script.onerror = () =>
      reject(
        new Error(
          `failed to load ${PDFIUM_SCRIPT_PATH} — see wasm.ts's asset-layout doc comment for what Task 9 needs to serve here`,
        ),
      );
    document.head.appendChild(script);
  });
}

let sessionPromise: Promise<WasmSessionHandle> | null = null;

/** Runs the init sequence exactly once (subsequent calls return the same
 * in-flight/settled promise) and returns the live `WasmSession`. Lazy
 * rather than run at module-evaluation time: this module has no
 * top-level `await` (the same constraint `index.ts` already documents —
 * `apps/desktop`'s configured esbuild target doesn't support it, and
 * this file is bundled by the exact same Vite config as `index.ts` when
 * `VITE_BACKEND=wasm`, so the constraint applies here too, not just
 * there), and every `Backend` method below calls this before touching
 * the session, so callers never have to think about init ordering
 * themselves. This is also what keeps `npm run check` and both
 * `vite build` directions green without ever loading real PDFium/wasm
 * assets: nothing at module scope calls this function, so neither
 * typecheck nor a production build ever executes `loadPdfiumScript`/the
 * dynamic imports below — they only run if something actually calls a
 * `wasmBackend` method at runtime, which no build or check step does. */
function ensureSession(): Promise<WasmSessionHandle> {
  if (!sessionPromise) {
    sessionPromise = initSession();
  }
  return sessionPromise;
}

async function initSession(): Promise<WasmSessionHandle> {
  await loadPdfiumScript();
  if (!window.PDFiumModule) {
    throw new Error(
      `${PDFIUM_SCRIPT_PATH} loaded but never defined window.PDFiumModule — wrong pdfium.js variant (see wasm.ts's asset-layout doc: it must be the classic-script "MODULARIZE=1 EXPORT_NAME=PDFiumModule" build, not pdfium.esm.js/pdfium.std.js)`,
    );
  }
  const pdfiumModule = await window.PDFiumModule();

  // Non-literal specifier + @vite-ignore: see the asset-layout comment
  // at the top of this file for why this particular import must stay
  // unresolved by the bundler (the opposite of index.ts's import of this
  // module, which must resolve for real).
  const wasmGluePath = WASM_GLUE_MODULE_PATH;
  const mod = (await import(/* @vite-ignore */ wasmGluePath)) as WasmModuleExports;
  const rustModule = await mod.default();

  // `rustModule` (i.e. `mod.default()`'s resolved value, the wasm-bindgen
  // `--target web` glue's `init()` return) has to be the *raw*
  // `WebAssembly.Instance.exports` object here, not some higher-level
  // wrapper — pdfium-render internally does `Reflect::get(local_module,
  // local_function_name)` to pull a named export off it and installs that
  // straight into Pdfium's own WASM indirect function table, which only
  // works if what comes back is the actual low-level exported function.
  // Under `--target web`, `openpdfedit_wasm.js`'s generated `init()` does
  // exactly `wasm = instance.exports; ...; return wasm;`, so `rustModule`
  // here already has that shape — no further unwrapping needed.
  //
  // This crate (pdfium-render 0.9.3) only name-installs one function this
  // way: `"write_block_from_callback_wasm"` (`wasm_bindings.rs` lines
  // 1808 and 1885, both on the write path) — `read_block_from_callback_wasm`
  // is `#[wasm_bindgen]`-exported (so it's present on `rustModule`/on
  // `InitOutput` in the generated `.d.ts`, 4-arg vs. the write path's
  // 3-arg) but never looked up by name anywhere in this crate version.
  // The write path only matters for `WasmSession::saveToBytes`'s
  // `FPDF_SaveAsCopy`/`FPDF_SaveWithVersion` call; `openDocument` goes
  // through `FPDF_LoadMemDocument64`, which copies the PDF bytes directly
  // and never touches the read/write-callback function-table machinery at
  // all — so `rustModule` being correct here is enough for every path
  // this backend actually exercises today.
  //
  // This is a summary, not the full investigation: the original read
  // pdfium-render 0.9.3's own source line-by-line to confirm the above
  // (which call sites, which arg counts, which path was actually
  // exercised) rather than assuming it from the API surface alone — see
  // `apps/extension/editor.ts` in the git history of commit `9e42968`
  // (the commit that deleted it, superseded by this file) for that
  // fuller archaeology if a future debugging session needs more than
  // this summary.
  const ok = mod.initialize_pdfium_render(pdfiumModule, rustModule, false);
  if (!ok) {
    throw new Error(
      "initialize_pdfium_render failed — pdfium.js/pdfium.wasm and the wasm-bindgen glue must be the matching build produced together by apps/extension/scripts/build-wasm.sh",
    );
  }

  return new mod.WasmSession();
}

// A module-scope `beforeunload` listener used to live here, closing every
// open engine handle unconditionally on page teardown. Deleted (Phase 2
// final-review C2): `beforeunload` listeners registered on `window` run in
// registration order, and this one ran *before* `onCloseRequested`'s own
// dirty-guard listener (registered later, from +page.svelte's `$effect`,
// which only fires after the component mounts — strictly after this
// module-scope statement would have run). That ordering broke the guard
// it was supposed to coexist with: with unsaved changes open, this
// listener closed every engine handle first, *then* the dirty-guard
// listener ran and called `preventDefault()`/showed the "Leave site?"
// prompt — correctly pausing the unload, but by then the handles were
// already dead. Cancelling that prompt (the whole point of asking) left
// the app running against closed PDFium documents: save/undo/render on
// the very document the prompt just "protected" would all fail.
//
// No replacement needed, and no `pagehide`/`visibilitychange` swap either:
// a page unload discards the wasm module's entire linear memory (and with
// it every PDFium-side document, byte buffer, and `MemWorkingStore` entry)
// regardless of whether this code ever ran `closeDocument` first — an
// early close here reclaimed nothing that outlived the page anyway, since
// there was no separate process for PDFium's state to leak into. The only
// real effect this listener ever had was the regression above; removing
// it is strictly a fix, not a tradeoff.

// A standalone `export async function initWasmBackend()` (a thin
// `ensureSession()` wrapper meant to let a caller warm the session up
// ahead of the first `Backend` call) used to live here. Removed as part
// of the Phase 5 Task 4 parked-minors sweep: it was never actually called
// anywhere — not by `index.ts`'s `initBackend()` (which only reads
// `mod.wasmBackend`, see that file), not by the extension bootstrap, not
// by any test — so the "Task 9's real extension bootstrap... can warm the
// session up" future it was written for never happened. Every `Backend`
// method below already calls `ensureSession()` itself (the whole reason
// this wrapper was ever "an optimization, never a requirement"), so
// nothing lost the ability to warm the session up by removing the unused
// standalone entry point; a real caller can still be added later if one
// ever needs it.

/** `mergeDocuments`/`compareDocuments` used to route through a sibling
 * `notImplemented` helper here ("not yet ported" — Phase 5 had a
 * concrete byte-based plan for them, see the Phase 4 ledger's Phase 5
 * notes); both are real as of Phase 5 Task 2, so that helper is gone —
 * every `Backend` method in this file is now either real or, for OCR
 * alone, genuinely unavailable. OCR was never "not yet" anything: the
 * desktop's tesseract-sidecar OCR path has no wasm story and was ruled
 * explicitly out of this port's scope, indefinitely, not just unported so
 * far (same ledger, "Explicitly NOT in this port's scope"). Saying "not
 * yet ported" for it would promise a future that isn't planned. */
function notAvailableInExtension(method: string): never {
  throw new Error(`not available in the extension: ${method}()`);
}

function parseOpenedDocument(json: string): OpenedDocument {
  return JSON.parse(json) as OpenedDocument;
}

// --- Open-document bookkeeping ------------------------------------------
//
// One `FileSystemFileHandle` per open document, keyed by the numeric
// handle `WasmSession.openDocument` hands back — this is what lets
// `saveDocument` write back to the same file the user opened, the same
// role `OpenDoc.original_path` plays on the desktop backend. Also caches
// the last DTO returned for that handle, used as a merge base for the one
// field `WasmSession` itself has no way to know: `file_path` (this
// backend's own `FileSystemFileHandle.name`-derived synthetic path, not
// anything `openpdfedit-session` tracks). Every other field in a save's
// return value — `is_dirty` in particular — comes from a real round trip
// into the session as of Phase 2 Task 2's `markSaved`
// (`WasmSession::mark_saved`, wrapping `openpdfedit_session::mark_saved`,
// which itself re-derives the DTO via `opened_document`): `saveDocument`/
// `saveDocumentAtPath` call it after their own file write succeeds and
// spread `file_path` from the cached entry over the fresh result, rather
// than cloning the cached DTO wholesale the way they used to before
// `markSaved` existed. `page_count`/`page_sizes`/`can_undo`/`can_redo` are
// real session state, not a client-side guess dressed up as one — and, as
// of Phase 2 Task 4, they can actually change: `addAnnotation`/
// `deleteAnnotation`/`undo`/`redo` are real mutations now (see the Rust
// module doc's "Annotation/undo surface" section).
//
// Handle rotation (Phase 2 Task 4): every mutating `WasmSession` method
// (`addAnnotation`/`deleteAnnotation`/`undo`/`redo`, same as
// `openpdfedit-session::reopen_after_write` on the desktop side) hands
// back an `OpenedDocumentInfo` under a **new** handle — the old one is
// gone; `reopen_after_write` already calls `engine.close(old_handle)`
// internally before installing the new one, so this backend must never
// call `WasmSession.closeDocument` on it too (that would double-close an
// already-closed engine handle). What *does* need to happen on this JS
// side, and wouldn't happen for free otherwise, is migrating the
// `openDocs` entry itself: this map is keyed by handle, so a mutation
// that doesn't move its `FileSystemFileHandle`/cached-`doc` entry over to
// the new key would leave the next `saveDocument`/`saveDocumentAtPath`
// call (`openDocs.get(newHandle)`, since `doc.handle` in +page.svelte is
// always the latest one) unable to find its file handle at all. See
// `migrateOpenDoc` below — the one helper every mutating `Backend` method
// in this file goes through.
//
// Document-closing policy (`WasmSession.closeDocument` call sites): as of
// Phase 2 Task 2, `Backend` gained a `closeDocument` method (see types.ts)
// and +page.svelte's `pickAndOpen` calls it on the *previously* open
// document once a new one has opened successfully (UI-layer placement —
// see that method's own comment for why: `doc.handle` there is always the
// UI's current-truth handle, including across the desktop's handle
// rotation on every edit, which neither backend module could reliably
// track on its own). This backend's `closeDocument` below is the
// counterpart to `openFromFileHandle`: it releases `WasmSession`'s
// engine-side state and drops the matching `openDocs` entry, mirroring
// the desktop's `close_document` Tauri command exactly. Before this task,
// nothing ever called it at all outside a module-scope `beforeunload`
// cleanup listener that used to live near the top of this file — this
// comment previously documented that gap as a Phase 2 follow-up; this is
// that follow-up landing. That `beforeunload` listener is gone now too
// (Phase 2 final-review C2 — see the deleted-listener comment right after
// `ensureSession`'s definition, for why): a page unload discards this whole
// wasm module's linear memory regardless of whether anything closed a
// document first, so there was never a real backstop to preserve — its
// only actual effect was a bug (see that comment).
interface OpenDocEntry {
  fileHandle: FileSystemFileHandle;
  doc: OpenedDocument;
}
const openDocs = new Map<number, OpenDocEntry>();

/** The shared tail every mutating `Backend` method below runs: parse a
 * `WasmSession` mutating call's `OpenedDocumentInfo` JSON, then migrate
 * `openDocs`'s bookkeeping from `oldHandle` (the handle the caller sent
 * in — `request.handle` for `addAnnotation`/`deleteAnnotation`, the plain
 * `handle` argument for `undo`/`redo`) to the fresh handle the session
 * just rotated onto. See the "Open-document bookkeeping" comment above
 * for why this migration has to happen at all, and why it must *not*
 * also call `session.closeDocument(oldHandle)` (already closed
 * engine-side by `reopen_after_write`).
 *
 * `file_path` is spread from the cached entry, not the fresh DTO — same
 * reasoning as `saveDocument`/`saveDocumentAtPath` above: the Rust
 * session's own `file_path` is frozen at `open_document`'s `display_name`
 * (see `OpenDoc::original_path`), while this backend's own
 * `FileSystemFileHandle.name` is the actual "Save" target of record once
 * a save-as has repointed it. `caller` is only used to make an
 * unknown-handle error legible about which `Backend` method hit it. */
function migrateOpenDoc(caller: string, oldHandle: number, freshJson: string): OpenedDocument {
  const entry = openDocs.get(oldHandle);
  if (!entry) {
    throw new Error(`${caller}: unknown document handle ${oldHandle}`);
  }
  openDocs.delete(oldHandle);
  const fresh = parseOpenedDocument(freshJson);
  const doc: OpenedDocument = { ...fresh, file_path: entry.doc.file_path };
  entry.doc = doc;
  openDocs.set(doc.handle, entry);
  return doc;
}

// `pickOpenPath`/`pickSavePath` return an opaque string "path" the way
// the `Backend` interface requires (mirroring the desktop's real
// filesystem paths), but there is no filesystem here — each call stashes
// the `FileSystemFileHandle` a picker actually returned under a fresh
// key, and `openDocument`/`saveDocumentAtPath` are the only things that
// ever look a key up. This is what lets +page.svelte's own two-step
// `pickOpenPath` + `openDocument` / `pickSavePath` +
// `saveDocumentAtPath` call patterns (see tauri.ts and task-7-report.md's
// "deliberate deviations" #1/#2) work unmodified against this backend
// too, not just the single-step `pickAndOpenDocument`/`saveDocumentAs`
// combos.
//
// The key is the picked `FileSystemFileHandle.name` itself (not an
// opaque counter like `picked-0`) — `+page.svelte`'s `pickAndOpen`/
// `saveDocumentAs` flows display this key verbatim in the path bar
// (`filePath = selected`/`filePath = target`, set before
// `openDocument`/`saveDocumentAtPath` resolves — see those call sites),
// so a counter-based key would show meaningless text like "picked-0"
// there instead of the file's actual name. Uniquified with a
// `" (2)"`/`" (3)"`/... suffix only on an actual collision (two pending
// picks with the same filename outstanding at once) via
// `uniquePickKey` below — the common case (one pick at a time) needs no
// suffix at all.
const pendingOpenPicks = new Map<string, FileSystemFileHandle>();
const pendingSavePicks = new Map<string, FileSystemFileHandle>();

/** Returns `name` unchanged if it's not already a key in `existing`,
 * otherwise `"name (2)"`, `"name (3)"`, ... — the first suffixed form
 * not already present. */
function uniquePickKey(name: string, existing: Map<string, FileSystemFileHandle>): string {
  if (!existing.has(name)) return name;
  let n = 2;
  while (existing.has(`${name} (${n})`)) {
    n++;
  }
  return `${name} (${n})`;
}

const PDF_TYPES = [{ description: "PDF", accept: { "application/pdf": [".pdf"] } }];

/** Builds `WasmSessionHandle.mergeDocuments`'s `sourcesBuffer` argument:
 * a flat concatenation of `[u32 length, little-endian][that many
 * bytes]` records, one per source, with no trailing padding — the JS-side
 * half of the length-prefixed-buffer design `WasmSession::merge_documents`'s
 * Rust doc explains (chosen over a stateful two-step begin/add/finish API
 * specifically so this side of the boundary stays this simple: one
 * `DataView`/`Uint8Array.set` pass, no session-lifecycle bookkeeping). */
function packLengthPrefixedSources(sources: Uint8Array[]): Uint8Array {
  const totalLength = sources.reduce((sum, source) => sum + 4 + source.length, 0);
  const buffer = new Uint8Array(totalLength);
  const view = new DataView(buffer.buffer);
  let offset = 0;
  for (const source of sources) {
    view.setUint32(offset, source.length, true);
    offset += 4;
    buffer.set(source, offset);
    offset += source.length;
  }
  return buffer;
}

/** `displayName` is passed straight through as `WasmSession.openDocument`'s
 * `display_name` argument, which becomes the returned `OpenedDocument`'s
 * `file_path` (see `OpenDoc::original_path` on the Rust side) — this backend's
 * *sole* caller (`wasmBackend.openDocument` below) always passes the exact
 * pick key it looked `fileHandle` up under in `pendingOpenPicks`, not
 * `file.name`/`fileHandle.name` (fix-round C1: those two used to be
 * independently derived — `pendingOpenPicks`' key carries a uniquifying
 * `" (2)"`/`" (3)"` suffix on a same-filename collision, `fileHandle.name`
 * never does — so `doc.file_path` could silently diverge from the pick key
 * `+page.svelte`'s `filePath` was set from, e.g. after `handleMerge`'s
 * save-cancel path left a stale pick sitting in `pendingOpenPicks` and
 * shifted the suffix for the next same-named pick. Passing the pick key
 * through here instead makes `filePath === doc.file_path` true by
 * construction, for every document this backend ever opens from a real
 * picker pick — see `mergeDocuments`/`extractPages`/`saveDocumentAtPath`
 * below for the other three call sites this same fix touches). */
async function openFromFileHandle(
  displayName: string,
  fileHandle: FileSystemFileHandle,
): Promise<OpenedDocument> {
  const session = await ensureSession();
  const file = await fileHandle.getFile();
  const bytes = new Uint8Array(await file.arrayBuffer());
  const doc = parseOpenedDocument(session.openDocument(displayName, bytes));
  openDocs.set(doc.handle, { fileHandle, doc });
  return doc;
}

async function writeToFileHandle(handle: number, fileHandle: FileSystemFileHandle): Promise<Uint8Array> {
  const session = await ensureSession();
  // workingCopyBytes, not saveToBytes: the working copy is what
  // commit_mutation/undo_impl/redo_impl actually wrote (an incremental,
  // append-only save) — the same bytes the desktop backend's own
  // save_document_impl writes to disk. saveToBytes is a full PDFium
  // rewrite, which would break byte-parity with the desktop and the
  // incremental-save/signature-preservation invariant (see
  // WasmSession::working_copy_bytes's Rust doc for the full rationale).
  const bytes = session.workingCopyBytes(handle);
  const writable = await fileHandle.createWritable();
  await writable.write(bytes);
  await writable.close();
  return bytes;
}

export const wasmBackend: Backend = {
  // --- document lifecycle (real) ---

  /** `path` here is one of `pickOpenPath`'s synthetic keys, not a real
   * filesystem path — see the "Open-document bookkeeping" comment above.
   * A `path` this backend never issued (e.g. a real path string, which
   * can't mean anything without a filesystem) fails with a clear error
   * rather than silently doing nothing. */
  async openDocument(path) {
    const fileHandle = pendingOpenPicks.get(path);
    if (!fileHandle) {
      throw new Error(
        `openDocument: "${path}" is not a pending picked file — the wasm backend has no filesystem, so this must be a key pickOpenPath() returned (see wasm.ts's "Open-document bookkeeping" doc)`,
      );
    }
    pendingOpenPicks.delete(path);
    return openFromFileHandle(path, fileHandle);
  },

  async pickAndOpenDocument() {
    const path = await wasmBackend.pickOpenPath();
    if (!path) return null;
    return wasmBackend.openDocument(path);
  },

  async saveDocument(handle) {
    const entry = openDocs.get(handle);
    if (!entry) throw new Error(`saveDocument: unknown document handle ${handle}`);
    await writeToFileHandle(handle, entry.fileHandle);
    // Mark clean only now that the write above has actually succeeded —
    // see WasmSession::mark_saved's Rust doc for why this ordering is the
    // whole point (a write that throws never reaches this line, so
    // is_dirty correctly stays whatever it was). Sourced from the real
    // session state (session.markSaved), not just a client-side `{ ...
    // is_dirty: false }` spread, so this stays correct once a mutation
    // surface actually lands on WasmSession and this flag can be true for
    // a real reason.
    const session = await ensureSession();
    const fresh = parseOpenedDocument(session.markSaved(handle));
    entry.doc = { ...fresh, file_path: entry.doc.file_path };
    return entry.doc;
  },

  async saveDocumentAtPath(handle, path) {
    const entry = openDocs.get(handle);
    if (!entry) throw new Error(`saveDocumentAtPath: unknown document handle ${handle}`);
    const fileHandle = pendingSavePicks.get(path);
    if (!fileHandle) {
      throw new Error(
        `saveDocumentAtPath: "${path}" is not a pending picked save target — must be a key pickSavePath() returned`,
      );
    }
    pendingSavePicks.delete(path);
    await writeToFileHandle(handle, fileHandle);
    // Future saves target the new location, same as the desktop's
    // save_document_as_impl reassigning OpenDoc.original_path.
    entry.fileHandle = fileHandle;
    // Same mark-clean-only-after-the-write-succeeds ordering as
    // saveDocument above.
    const session = await ensureSession();
    const fresh = parseOpenedDocument(session.markSaved(handle));
    // `file_path: path` (the pick key this call was invoked with), not
    // `fileHandle.name` — same fix-round C1 namespace-unification as
    // `openFromFileHandle` above: `path` is exactly what `+page.svelte`'s
    // `filePath` was set to right before this call (`handleSaveAs`/
    // `handleMerge`'s own `filePath = target`/`filePath = outputPath`), so
    // this keeps `filePath === doc.file_path` true by construction instead
    // of relying on the two happening to agree.
    entry.doc = { ...fresh, file_path: path };
    return entry.doc;
  },

  /** Releases `handle`'s engine-side state and this backend's own
   * `openDocs` bookkeeping — see the "Document-closing policy" comment
   * above for when this is (and isn't) called. */
  async closeDocument(handle) {
    const session = await ensureSession();
    session.closeDocument(handle);
    openDocs.delete(handle);
  },

  async saveDocumentAs(handle, defaultPath) {
    const target = await wasmBackend.pickSavePath(defaultPath ?? undefined);
    if (!target) return null;
    return wasmBackend.saveDocumentAtPath(handle, target);
  },

  /** Documented no-op (Phase 5 final-review fix round, M1 — previously
   * called `window.close()`). `confirmClose`'s only real caller anywhere
   * in this app is +page.svelte's `onCloseRequested` callback, *after*
   * its own app-level "Unsaved changes" modal resolves — and, as of this
   * same fix round, `onCloseRequested` below never invokes that callback
   * on the wasm backend at all (see its doc for why), so this method is
   * provably unreachable in the extension today, not just untested. Kept
   * as a real (if inert) `Backend` method rather than deleted: the
   * interface still declares it (the desktop backend's own
   * `close_window` implementation is real and load-bearing there), and a
   * future extension chrome that gains an actual "close this tab/window"
   * affordance of its own gets a real hook to fill in here instead of
   * having to add one from scratch. `window.close()`'s old behavior was
   * never reachable *usefully* either — browsers refuse to script-close a
   * tab the page itself didn't open via `window.open()`, and a real
   * extension tab is opened by the user, not by this page — so this
   * change removes a call that could only ever silently no-op via its own
   * `catch`, not a working code path. */
  async confirmClose() {},

  /** `beforeunload` is the only "the tab wants to close, decide first"
   * signal a browser page gets — unlike Tauri's `close-requested` event,
   * there is no way to pause the close and let arbitrary async JS (e.g.
   * a custom "Save before closing?" modal) run before deciding; the only
   * lever is the synchronous `preventDefault()`/`returnValue` contract,
   * which triggers the browser's own native "Leave site?" confirmation
   * prompt — not a custom one, and not one this code can await the
   * outcome of.
   *
   * `cb` is deliberately never called here (Phase 5 final-review fix
   * round, M1 — it used to be, right alongside `preventDefault()`). `cb`
   * is +page.svelte's own async callback
   * (`confirmProceedDespiteUnsavedChanges("close")` then
   * `backend.confirmClose()`) — the app-level "Unsaved changes: Save /
   * Discard / Cancel" modal that drives the *desktop* backend's real
   * close flow (Tauri's `close-requested` event, which genuinely can
   * pause the close for that modal to run). Calling it here bought
   * nothing and was actively misleading: by the time `cb` could show that
   * modal, the *decision* about whether to block the close was already
   * made — synchronously, via `preventDefault()`/`returnValue` above, in
   * the same tick — and the browser's own native prompt is what the user
   * actually sees and answers. The app's modal would render behind (or
   * racing) that native prompt, capture no real answer from it (the user
   * already answered the *browser's* prompt, not this one), and its own
   * `backend.confirmClose()` tail call was already a no-op (see that
   * method's doc). Net effect pre-fix: a dead, confusing modal flash with
   * no actual say in whether the tab closed — never the guard it looked
   * like. The real guard, and the only one that exists here, is the
   * native prompt this handler's `preventDefault()` triggers. */
  async onCloseRequested() {
    const handler = (e: BeforeUnloadEvent) => {
      const anyDirty = [...openDocs.values()].some((entry) => entry.doc.is_dirty);
      if (anyDirty) {
        e.preventDefault();
        e.returnValue = "";
      }
    };
    window.addEventListener("beforeunload", handler);
    return () => window.removeEventListener("beforeunload", handler);
  },

  async undo(handle) {
    const session = await ensureSession();
    const json = session.undo(handle);
    return migrateOpenDoc("undo", handle, json);
  },

  async redo(handle) {
    const session = await ensureSession();
    const json = session.redo(handle);
    return migrateOpenDoc("redo", handle, json);
  },

  // --- rendering (real) ---

  async getPageBitmap(handle, pageIndex, targetWidth, signal) {
    if (signal?.aborted) {
      throw new DOMException("aborted before rendering started", "AbortError");
    }
    const session = await ensureSession();
    const page = session.renderPage(handle, pageIndex, targetWidth);
    try {
      if (signal?.aborted) {
        throw new DOMException("aborted after rendering completed", "AbortError");
      }
      // `page.rgba`'s getter (`js_sys::Uint8Array::from(self.rgba.as_slice())`
      // on the Rust side, per RenderedPage's impl) already *copies* the
      // pixels into a standalone JS-heap Uint8Array *every time it's
      // read* — it is not a live view into wasm linear memory, and it is
      // not cached on the JS side either. Read it exactly once into
      // `rgba` below and build the view off that: three separate
      // `page.rgba` reads (one per property, as a naive object-literal
      // construction would do) would silently do three full-bitmap
      // copies of the same pixels on every single tile paint. The
      // `Uint8ClampedArray` below is itself just a *view* over `rgba`'s
      // buffer (no further copy), and stays valid after `page.free()`
      // runs in the `finally` block below: `free()` only drops the
      // Rust-side `Vec<u8>` this JS array was copied from, it doesn't
      // touch the copy itself.
      const rgba = page.rgba;
      const bitmap: PageBitmap = {
        width: page.width,
        height: page.height,
        rgba: new Uint8ClampedArray(rgba.buffer, rgba.byteOffset, rgba.byteLength),
      };
      return bitmap;
    } finally {
      // Deterministic cleanup on the hot scroll path: `RenderedPage` owns
      // a `Vec<u8>` of rendered pixels on the *wasm* side with no GC to
      // reclaim it — see `RenderedPageHandle`'s doc. Freeing it here
      // doesn't touch `bitmap.rgba` above (already copied out, per the
      // comment there). `finally` so this still runs on the
      // abort-after-render throw.
      page.free();
    }
  },

  // --- annotations (real, Phase 2 Task 4) ---

  /** Read-only — no `openDocs` migration needed (see the "Handle
   * rotation" comment above `migrateOpenDoc`). */
  async listPageAnnotations(handle, pageIndex) {
    const session = await ensureSession();
    const json = session.listPageAnnotations(handle, pageIndex);
    return JSON.parse(json) as AnnotationSummaryDto[];
  },

  async addAnnotation(request: AddAnnotationRequest) {
    const session = await ensureSession();
    const json = session.addAnnotation(JSON.stringify(request));
    return migrateOpenDoc("addAnnotation", request.handle, json);
  },

  async deleteAnnotation(request: DeleteAnnotationRequest) {
    const session = await ensureSession();
    const json = session.deleteAnnotation(JSON.stringify(request));
    return migrateOpenDoc("deleteAnnotation", request.handle, json);
  },

  /** Read-only — no `openDocs` migration needed, same as
   * `listPageAnnotations` above. */
  async textSelectionQuads(request: TextSelectionQuadsRequest) {
    const session = await ensureSession();
    const json = session.textSelectionQuads(JSON.stringify(request));
    return JSON.parse(json) as [number, number, number, number][];
  },

  // --- forms (real, Phase 3 Task 3) ---

  /** Read-only — no `openDocs` migration needed, same as
   * `listPageAnnotations` above. */
  async listFormFields(handle) {
    const session = await ensureSession();
    const json = session.listFormFields(handle);
    return JSON.parse(json) as FormFieldDto[];
  },

  async fillFormFields(request: FillFormFieldsRequest) {
    const session = await ensureSession();
    const json = session.fillFormFields(JSON.stringify(request));
    return migrateOpenDoc("fillFormFields", request.handle, json);
  },

  async createFormField(request: CreateFormFieldRequest) {
    const session = await ensureSession();
    const json = session.createFormField(JSON.stringify(request));
    return migrateOpenDoc("createFormField", request.handle, json);
  },

  // --- pages (real, Phase 3 Task 3) ---

  async rotatePage(handle, pageIndex, deltaDegrees) {
    const session = await ensureSession();
    const json = session.rotatePage(handle, pageIndex, deltaDegrees);
    return migrateOpenDoc("rotatePage", handle, json);
  },

  async deletePage(handle, pageIndex) {
    const session = await ensureSession();
    const json = session.deletePage(handle, pageIndex);
    return migrateOpenDoc("deletePage", handle, json);
  },

  async movePage(handle, pageIndex, direction) {
    const session = await ensureSession();
    const json = session.movePage(handle, pageIndex, direction);
    return migrateOpenDoc("movePage", handle, json);
  },

  async setCropBox(handle, pageIndex, rect) {
    const session = await ensureSession();
    const json = session.setCropBox(handle, pageIndex, Float32Array.from(rect));
    return migrateOpenDoc("setCropBox", handle, json);
  },

  /** Deliberately not a `migrateOpenDoc` call — unlike every other
   * mutating method in this file, extraction doesn't rotate the *source*
   * document's handle at all (it stays open, untouched, exactly like the
   * desktop's `extract_pages_impl`); it opens a brand-new, independent
   * document instead. `request.outputPath` is one of `pickSavePath`'s
   * synthetic keys (see this file's "Open-document bookkeeping" comment
   * and `pickSavePath` below) — `+page.svelte`'s `handleExtractSelected`
   * already calls `pickSavePath` before this method, exactly like the
   * desktop backend's own call site, so this works unmodified against
   * `types.ts`'s existing `Backend.extractPages` signature.
   *
   * `WasmSession.extractPages` returns only the extracted document's raw
   * bytes (no filesystem to open a new document *from* on this backend's
   * side — see that method's Rust doc) — this method is what turns those
   * bytes into a real `OpenedDocument`: write them to the picked
   * `FileSystemFileHandle` (so a subsequent `saveDocument` on the new
   * handle has somewhere to write back to, mirroring the desktop's
   * `open_new_file` opening the just-written `output_path`), then open
   * the same bytes as a new session document, exactly like
   * `openFromFileHandle` does for a real file pick. */
  async extractPages(request: ExtractPagesRequest) {
    const fileHandle = pendingSavePicks.get(request.outputPath);
    if (!fileHandle) {
      throw new Error(
        `extractPages: "${request.outputPath}" is not a pending picked save target — must be a key pickSavePath() returned`,
      );
    }
    pendingSavePicks.delete(request.outputPath);

    const session = await ensureSession();
    const bytes = session.extractPages(
      JSON.stringify({ handle: request.handle, pageIndices: request.pageIndices }),
    );

    const writable = await fileHandle.createWritable();
    await writable.write(bytes);
    await writable.close();

    // request.outputPath, not fileHandle.name, as the display name — same
    // fix-round C1 namespace-unification as openFromFileHandle above:
    // request.outputPath is the exact pickSavePath() key +page.svelte's
    // filePath gets set to right after this call resolves
    // (handleExtractSelected's own `filePath = outputPath`).
    const doc = parseOpenedDocument(session.openDocument(request.outputPath, bytes));
    openDocs.set(doc.handle, { fileHandle, doc });
    return doc;
  },

  /** Compress-copy export, built entirely from already-exported wasm
   * primitives: `saveToBytes` (the full PDFium rewrite — no revision
   * chain, no orphans) for the output, `workingCopyBytes` for the
   * before-size, and the picked save target for the write. Export, not
   * mutation — no handle rotation, `openDocs` untouched. */
  async compressDocument(request: CompressDocumentRequest): Promise<CompressStats> {
    const fileHandle = pendingSavePicks.get(request.outputPath);
    if (!fileHandle) {
      throw new Error(
        `compressDocument: "${request.outputPath}" is not a pending picked save target — must be a key pickSavePath() returned`,
      );
    }
    pendingSavePicks.delete(request.outputPath);

    const session = await ensureSession();
    const beforeBytes = session.workingCopyBytes(request.handle).byteLength;
    const bytes = session.saveToBytes(request.handle);

    const writable = await fileHandle.createWritable();
    await writable.write(bytes);
    await writable.close();

    return { beforeBytes, afterBytes: bytes.byteLength };
  },

  // --- signatures/redact/textedit/image (real, Phase 4 Task 3) ---

  /** Read-only — no `openDocs` migration needed, same as
   * `listPageAnnotations` above. Structural inspection only — see
   * `SignatureInfoDto`'s own doc in types.ts: `isVerified` is always
   * `false`. This is the call `+page.svelte`'s `refreshSignatures` makes
   * after open and after a form fill — see that function's doc for why
   * a fill (a full PDFium rewrite, unlike every other mutating method in
   * this file) is the one write path signatures must be re-fetched
   * around; that refetch-after-fill call site already existed (it just
   * threw via `notImplemented` until now). */
  async listSignatures(handle) {
    const session = await ensureSession();
    const json = session.listSignatures(handle);
    return JSON.parse(json) as SignatureInfoDto[];
  },

  async searchDocument(request) {
    const session = await ensureSession();
    const json = session.searchDocument(
      request.handle,
      request.query,
      request.matchCase,
      request.wholeWord,
    );
    return JSON.parse(json) as SearchResultsDto;
  },

  async redactPage(request: RedactPageRequest) {
    const session = await ensureSession();
    const json = session.redactPage(JSON.stringify(request));
    return migrateOpenDoc("redactPage", request.handle, json);
  },

  async applyWatermark(request: ApplyWatermarkRequest) {
    const session = await ensureSession();
    const json = session.applyWatermark(JSON.stringify(request));
    return migrateOpenDoc("applyWatermark", request.handle, json);
  },

  /** Read-only — no `openDocs` migration needed, same as
   * `listPageAnnotations` above. */
  async listTextRuns(handle, pageIndex) {
    const session = await ensureSession();
    const json = session.listTextRuns(handle, pageIndex);
    return JSON.parse(json) as TextRunDto[];
  },

  async editTextRun(request: EditTextRunRequest) {
    const session = await ensureSession();
    const json = session.editTextRun(JSON.stringify(request));
    return migrateOpenDoc("editTextRun", request.handle, json);
  },

  async moveTextRun(request: MoveTextRunRequest) {
    const session = await ensureSession();
    const json = session.moveTextRun(JSON.stringify(request));
    return migrateOpenDoc("moveTextRun", request.handle, json);
  },

  /** Read-only — no `openDocs` migration needed, same as
   * `listPageAnnotations` above. */
  async listImagePlacements(handle, pageIndex) {
    const session = await ensureSession();
    const json = session.listImagePlacements(handle, pageIndex);
    return JSON.parse(json) as ImagePlacementDto[];
  },

  async moveImage(request: MoveImageRequest) {
    const session = await ensureSession();
    const json = session.moveImage(JSON.stringify(request));
    return migrateOpenDoc("moveImage", request.handle, json);
  },

  // --- document-level tools (real, Phase 5 Task 2) — OCR excepted: not
  // available, indefinitely, not just unported (see
  // notAvailableInExtension above) ---

  /** `request.sourcePaths` are `pickOpenPaths()` keys (raw, never-opened
   * picks — this method reads their bytes directly off the picked
   * `FileSystemFileHandle`s and consumes them from `pendingOpenPicks`,
   * mirroring `openDocument`'s own resolution); `request.outputPath` is a
   * `pickSavePath()` key, exactly like `extractPages` above. Mirrors that
   * method's landed pattern end to end: no `migrateOpenDoc` call, since
   * (matching the desktop's `merge_documents_impl`/`gather_merge_sources`)
   * a merge never rotates or otherwise touches the *source* document at
   * `request.openHandle` — only the brand-new merged document gets
   * opened, under its own fresh handle. The open document's live,
   * possibly-unsaved bytes (if `openHandle` is set) are resolved
   * session-side, through `WorkingStore`, not read from this file at all
   * — see `WasmSession::merge_documents`'s Rust doc.
   *
   * **Deliberately does not close `request.openHandle`'s `openDocs` entry
   * either** (a fix-round question, not an oversight): the desktop
   * backend doesn't close it — `merge_documents_impl`/
   * `gather_merge_sources` only ever *read* `docs[open_handle]`, never
   * remove it — so this backend closing it here would be a real
   * behavioral divergence, not a harmless symmetric cleanup, even though
   * `+page.svelte`'s `handleMerge` immediately moves `doc` on to the
   * merged result and never interacts with the old handle again (unlike
   * `pickAndOpen`, which *does* close the document it's replacing — see
   * that method's own doc for why that case is different: there, `doc`
   * itself is being replaced, the exact one place this file's header
   * comment identifies as needing a close). One real consequence: two
   * live `openDocs` entries can end up sharing one `file_path` if the
   * merged output is saved under the same filename as one of its sources
   * — `compareDocuments`'s `pathA` resolution below is written to stay
   * correct under exactly that, see its own doc for how. */
  async mergeDocuments(request: MergeDocumentsRequest) {
    const fileHandle = pendingSavePicks.get(request.outputPath);
    if (!fileHandle) {
      throw new Error(
        `mergeDocuments: "${request.outputPath}" is not a pending picked save target — must be a key pickSavePath() returned`,
      );
    }
    pendingSavePicks.delete(request.outputPath);

    const sourceBuffers: Uint8Array[] = [];
    for (const sourcePath of request.sourcePaths) {
      const sourceHandle = pendingOpenPicks.get(sourcePath);
      if (!sourceHandle) {
        throw new Error(
          `mergeDocuments: "${sourcePath}" is not a pending picked file — must be a key pickOpenPaths() returned`,
        );
      }
      pendingOpenPicks.delete(sourcePath);
      const file = await sourceHandle.getFile();
      sourceBuffers.push(new Uint8Array(await file.arrayBuffer()));
    }

    const session = await ensureSession();
    const bytes = session.mergeDocuments(
      JSON.stringify({ openHandle: request.openHandle }),
      packLengthPrefixedSources(sourceBuffers),
    );

    const writable = await fileHandle.createWritable();
    await writable.write(bytes);
    await writable.close();

    // request.outputPath, not fileHandle.name, as the display name — same
    // fix-round C1 namespace-unification as openFromFileHandle/extractPages
    // above: request.outputPath is the exact pickSavePath() key
    // +page.svelte's filePath gets set to right after this call resolves
    // (handleMerge's own `filePath = outputPath`).
    const doc = parseOpenedDocument(session.openDocument(request.outputPath, bytes));
    openDocs.set(doc.handle, { fileHandle, doc });
    return doc;
  },

  /** No `types.ts`/`Backend` interface change needed — `+page.svelte`'s
   * `handleCompareDocument` already sends two opaque path *strings*
   * (`pathA`/`pathB`), and this backend already treats every `Backend`
   * "path" as an opaque, backend-defined key (see the "Open-document
   * bookkeeping" comment above); compare just needed the right resolution
   * for each side, not a new field:
   *
   * - `pathA` is always `filePath` — the *currently open* document's
   *   synthetic path (+page.svelte sets `filePath` once, from
   *   `pickOpenPath`/`pickSavePath`, and never re-derives it from
   *   `doc.file_path` on a plain mutation) — which is why it can't be
   *   resolved through `pendingOpenPicks` the way `extractPages`'s
   *   `outputPath` is: that map entry was already deleted the moment this
   *   document was opened. Resolved instead by scanning `openDocs` for
   *   the entry whose cached `file_path` matches, then reading its
   *   **live working-copy** bytes via `workingCopyBytes` — the same
   *   live-copy semantic `mergeDocuments`'s `openHandle` source uses on
   *   the session side, so an in-progress unsaved edit is compared, not a
   *   stale on-open snapshot.
   *
   *   **Why the *last* match, not the first** (fix-round finding):
   *   `openDocs` can hold more than one live entry with the same
   *   `file_path` — `mergeDocuments` deliberately never closes its
   *   `openHandle` source (see that method's own doc: matching the
   *   desktop's `merge_documents_impl`/`gather_merge_sources`, which also
   *   never touches `docs[open_handle]`, so closing it here would be a
   *   real behavioral divergence from the desktop backend, not a
   *   harmless cleanup), so a merge followed by saving the result under
   *   the *same* filename as one of its sources leaves two live
   *   `openDocs` entries sharing one `file_path`: the stale pre-merge
   *   source and the new merged document. A first-match scan can hand
   *   `compareDocuments` the stale one. `openDocs` iterates in insertion
   *   order, and every place this file gives a document a fresh identity
   *   for a path — `openFromFileHandle`, `mergeDocuments`/`extractPages`'
   *   own `openDocs.set` tail, and `migrateOpenDoc`'s `delete` + `set`
   *   under the rotated handle on every mutation — either appends a new
   *   key or (for `migrateOpenDoc`) deletes-then-reinserts under a new
   *   key, which JS `Map` always appends at the end regardless of the
   *   deleted key's old position. So the *last* matching entry in
   *   iteration order is always the one most recently given this path —
   *   exactly "the currently open document" `filePath` is tracking —
   *   while a stale, never-closed entry like a leaked merge source can
   *   only ever appear *earlier*, never later, than the document that
   *   superseded it. No interface change, no closing anything extra:
   *   this only fixes which of several already-live candidates compare
   *   picks.
   * - `pathB` is a fresh `pickOpenPath()` result that was never opened as
   *   a document (`handleCompareDocument` passes it straight to
   *   `compareDocuments`) — still sitting in `pendingOpenPicks`, so it's
   *   read directly off its `FileSystemFileHandle`, the same as any other
   *   pending-pick resolution in this file. */
  async compareDocuments(request: CompareDocumentsRequest) {
    const session = await ensureSession();

    let matchedHandle: number | undefined;
    for (const entry of openDocs.values()) {
      if (entry.doc.file_path === request.pathA) {
        matchedHandle = entry.doc.handle;
      }
    }
    if (matchedHandle === undefined) {
      throw new Error(`compareDocuments: "${request.pathA}" is not a currently open document`);
    }
    const bytesA = session.workingCopyBytes(matchedHandle);

    const fileHandleB = pendingOpenPicks.get(request.pathB);
    if (!fileHandleB) {
      throw new Error(
        `compareDocuments: "${request.pathB}" is not a pending picked file — must be a key pickOpenPath() returned`,
      );
    }
    pendingOpenPicks.delete(request.pathB);
    const fileB = await fileHandleB.getFile();
    const bytesB = new Uint8Array(await fileB.arrayBuffer());

    const json = session.compareDocuments(
      bytesA,
      bytesB,
      JSON.stringify({ pixelTargetWidth: request.pixelTargetWidth }),
    );
    return JSON.parse(json) as CompareReportDto;
  },

  async ocrDocument() {
    return notAvailableInExtension("ocrDocument");
  },

  // --- file-picker primitives (real — open/save-as depend on these) ---

  async pickOpenPath() {
    let handles: FileSystemFileHandle[];
    try {
      handles = await window.showOpenFilePicker({ multiple: false, types: PDF_TYPES });
    } catch (e) {
      if ((e as { name?: string })?.name === "AbortError") return null;
      throw e;
    }
    const fileHandle = handles[0];
    if (!fileHandle) return null;
    const key = uniquePickKey(fileHandle.name, pendingOpenPicks);
    pendingOpenPicks.set(key, fileHandle);
    return key;
  },

  /** `handleMerge` in +page.svelte calls this to gather merge sources,
   * then feeds the returned keys straight into `mergeDocuments({
   * sourcePaths, ... })` above — real end to end as of Phase 5 Task 2 (it
   * used to dead-end there: this method existed since Phase 2 Task 4, but
   * `mergeDocuments` itself threw via a since-removed `notImplemented`
   * helper, so a merge attempt failed with a clear "not yet ported" error
   * banner once it reached that call). The two picker calls below stay
   * wrapped in their own try/catch regardless (rather than left bare) so
   * a backend that can't fulfil a picker call surfaces through the same
   * error banner (`error = formatError(e)`) every other failure in this
   * flow already uses, instead of an unhandled promise rejection nothing
   * on screen reflects — `handleMerge`'s picker calls aren't wrapped in a
   * try/catch of their own. */
  async pickOpenPaths() {
    let handles: FileSystemFileHandle[];
    try {
      handles = await window.showOpenFilePicker({ multiple: true, types: PDF_TYPES });
    } catch (e) {
      if ((e as { name?: string })?.name === "AbortError") return [];
      throw e;
    }
    return handles.map((fileHandle) => {
      const key = uniquePickKey(fileHandle.name, pendingOpenPicks);
      pendingOpenPicks.set(key, fileHandle);
      return key;
    });
  },

  async pickSavePath(defaultPath) {
    let fileHandle: FileSystemFileHandle;
    try {
      fileHandle = await window.showSaveFilePicker({ suggestedName: defaultPath, types: PDF_TYPES });
    } catch (e) {
      if ((e as { name?: string })?.name === "AbortError") return null;
      throw e;
    }
    const key = uniquePickKey(fileHandle.name, pendingSavePicks);
    pendingSavePicks.set(key, fileHandle);
    return key;
  },

  /** Deletes `paths` from both pending-pick maps — see types.ts's
   * `Backend.releasePicks` doc for when a caller needs this (an abandoned
   * pick that never reached `openDocument`/`mergeDocuments`/etc.) and
   * wasm.ts's "Open-document bookkeeping" doc for why leaving one behind
   * forever is a real (if narrow) bug: `uniquePickKey` only suffixes a key
   * on an actual collision with a still-present entry, so an abandoned,
   * never-released pick permanently steals that filename's un-suffixed
   * key from every later legitimate pick of the same name. Tries both
   * maps unconditionally rather than requiring the caller to know which
   * one a given path came from (`pickOpenPath(s)` vs. `pickSavePath`) —
   * harmless: `Map.delete` on an absent key is a no-op. */
  async releasePicks(paths) {
    for (const path of paths) {
      pendingOpenPicks.delete(path);
      pendingSavePicks.delete(path);
    }
  },
};
